/**
 * Base de regles de securite par motifs, multi-langages.
 *
 * Chaque regle : { id, title, severity, families, pattern, message, suggestion,
 * cwe, owasp, confidence, effort, ignoreIf }.
 * `families` = familles de langages concernees (voir languages.js), `*` = toutes.
 * Les motifs sont appliques sur le code masque (commentaires/chaines neutralises)
 * sauf si `raw: true`.
 */

export const SECURITY_RULES = [
  // ---------------------------------------------------------------- Injection
  {
    id: 'SEC-EVAL',
    // La gravite depend de l'origine de la valeur concatenee : le flux
    // de donnees est consulte quand le fichier est du JavaScript.
    fluxDeDonnees: true,
    title: 'Execution de code dynamique (eval)',
    severity: 'high',
    families: ['js', 'python', 'php', 'ruby'],
    pattern: /(?<![\w$.])eval\s*\(/g,
    message: 'Appel a eval() : tout contenu controle par l\'utilisateur devient du code executable.',
    suggestion: 'Remplacez eval par JSON.parse pour des donnees, ou par une table de correspondance explicite pour du dispatch dynamique.',
    cwe: 'CWE-95',
    owasp: 'A03:2021 Injection',
    effort: 'moyen',
  },
  {
    id: 'SEC-FUNCTION-CTOR',
    title: 'Constructeur Function dynamique',
    severity: 'high',
    families: ['js'],
    pattern: /new\s+Function\s*\(/g,
    message: 'new Function() compile une chaine en code : equivalent a eval.',
    suggestion: 'Utilisez une fonction reelle ou un mapping de comportements.',
    cwe: 'CWE-95',
    owasp: 'A03:2021 Injection',
  },
  {
    id: 'SEC-EXEC-SHELL',
    title: 'Commande shell avec interpolation',
    severity: 'critical',
    families: ['js', 'python', 'php', 'ruby', 'go', 'jvm'],
    pattern: /(exec|execSync|spawnSync|system|popen|shell_exec|passthru|Runtime\.getRuntime\(\)\.exec)\s*\(\s*[^)]*(\$\{|\+\s*\w|%s|f["']|\.format\(|`)/g,
    message: 'Construction d\'une commande systeme par concatenation : injection de commande possible.',
    suggestion: 'Passez les arguments sous forme de tableau (execFile / spawn / subprocess.run([...])) et n\'utilisez jamais shell:true avec une entree utilisateur.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    effort: 'moyen',
  },
  {
    id: 'SEC-SHELL-TRUE',
    title: 'subprocess avec shell=True',
    severity: 'high',
    families: ['python'],
    pattern: /subprocess\.(run|call|check_output|Popen)\s*\([^)]*shell\s*=\s*True/g,
    message: 'shell=True expose a l\'injection de commande des qu\'une variable entre dans la commande.',
    suggestion: 'Passez une liste d\'arguments : subprocess.run(["ls", "-l", chemin]).',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
  },
  {
    id: 'SEC-SQL-CONCAT',
    // La gravite depend de l'origine de la valeur concatenee : le flux
    // de donnees est consulte quand le fichier est du JavaScript.
    fluxDeDonnees: true,
    title: 'Requete SQL construite par concatenation',
    severity: 'critical',
    families: ['*'],
    // `raw` : la requete vit dans une chaine de caracteres, que le masquage
    // neutralise. Cette regle doit donc lire le code d'origine.
    raw: true,
    // La forme complete de la requete est exigee (`UPDATE … SET`, `SELECT …
    // FROM`) : sans cela, un simple appel a `update(...)` suffirait a declencher.
    pattern: /(?:SELECT\s+[\w*,.\s()]{1,120}?\s+FROM|INSERT\s+INTO\s+[\w.`"[\]]+|UPDATE\s+[\w.`"[\]]+\s+SET|DELETE\s+FROM\s+[\w.`"[\]]+)[^;\n]{0,200}?(["'`]\s*\+\s*\w|\$\{|%\s*\(|%s\b|["']\s*\.\s*\$|\|\|\s*\w)/gi,
    message: 'Une requete SQL est assemblee avec des variables : injection SQL probable.',
    suggestion: 'Utilisez des requetes parametrees (placeholders ? / $1 / :nom) fournies par votre driver ou ORM.',
    cwe: 'CWE-89',
    owasp: 'A03:2021 Injection',
    effort: 'moyen',
  },
  {
    id: 'SEC-SQL-RAW',
    title: 'Requete SQL brute d\'ORM',
    severity: 'medium',
    families: ['*'],
    pattern: /\.(raw|rawQuery|executeRawUnsafe|queryRawUnsafe|extra)\s*\(\s*[`'"]/g,
    message: 'Requete SQL brute : verifiez que les parametres ne sont pas interpoles.',
    suggestion: 'Preferez le query builder, ou passez les valeurs via le tableau de parametres de la methode raw.',
    cwe: 'CWE-89',
    confidence: 'tentative',
  },
  {
    id: 'SEC-NOSQL-WHERE',
    // La gravite depend de l'origine de la valeur concatenee : le flux
    // de donnees est consulte quand le fichier est du JavaScript.
    fluxDeDonnees: true,
    title: 'Operateur $where MongoDB',
    severity: 'high',
    families: ['js', 'python'],
    pattern: /\$where\s*[:=]/g,
    message: '$where evalue du JavaScript cote base : injection NoSQL possible.',
    suggestion: 'Remplacez par des operateurs de requete standards ($eq, $gt, $in).',
    cwe: 'CWE-943',
  },

  // ------------------------------------------------------------------- XSS
  {
    id: 'SEC-INNERHTML',
    title: 'Ecriture HTML non echappee (innerHTML)',
    severity: 'high',
    families: ['js'],
    pattern: /\.(innerHTML|outerHTML)\s*=\s*(?!['"`]\s*['"`])/g,
    message: 'Affectation directe de innerHTML : XSS si la valeur vient de l\'utilisateur.',
    suggestion: 'Utilisez textContent, ou assainissez avec DOMPurify.sanitize() avant insertion.',
    cwe: 'CWE-79',
    owasp: 'A03:2021 Injection',
  },
  {
    id: 'SEC-DANGEROUS-HTML',
    title: 'dangerouslySetInnerHTML',
    severity: 'high',
    families: ['js'],
    pattern: /dangerouslySetInnerHTML/g,
    message: 'React desactive son echappement automatique a cet endroit.',
    suggestion: 'Assainissez le HTML (DOMPurify) ou rendez le contenu comme du texte.',
    cwe: 'CWE-79',
  },
  {
    id: 'SEC-VUE-VHTML',
    title: 'Directive v-html',
    severity: 'high',
    families: ['js', 'markup'],
    pattern: /v-html\s*=/g,
    raw: true,
    message: 'v-html injecte du HTML brut dans le DOM.',
    suggestion: 'Utilisez l\'interpolation {{ }} ou assainissez la valeur cote serveur.',
    cwe: 'CWE-79',
  },
  {
    id: 'SEC-DOC-WRITE',
    title: 'document.write',
    severity: 'medium',
    families: ['js'],
    pattern: /document\.write(ln)?\s*\(/g,
    message: 'document.write bloque le rendu et ouvre une surface XSS.',
    suggestion: 'Construisez les noeuds via createElement/textContent.',
    cwe: 'CWE-79',
  },
  {
    id: 'SEC-TEMPLATE-AUTOESCAPE',
    title: 'Echappement de template desactive',
    severity: 'high',
    families: ['python', 'php', 'js', 'markup'],
    pattern: /(autoescape\s*=\s*False|\|\s*safe\b|\{!!|@php\s*echo|mark_safe\s*\()/g,
    raw: true,
    message: 'L\'echappement automatique du moteur de template est contourne.',
    suggestion: 'Ne desactivez l\'echappement que sur du contenu que vous avez vous-meme assaini.',
    cwe: 'CWE-79',
  },

  // ------------------------------------------------------- Deserialisation
  {
    id: 'SEC-PICKLE',
    title: 'Deserialisation non sure (pickle/yaml)',
    severity: 'critical',
    families: ['python'],
    pattern: /(pickle\.loads?|cPickle\.loads?|yaml\.load\s*\((?![^)]*Loader\s*=\s*yaml\.SafeLoader)|marshal\.loads?)\s*\(/g,
    message: 'Deserialisation capable d\'executer du code arbitraire.',
    suggestion: 'Utilisez json.loads, ou yaml.safe_load. Ne desserialisez jamais une source non fiable.',
    cwe: 'CWE-502',
    owasp: 'A08:2021 Data Integrity Failures',
  },
  {
    id: 'SEC-JAVA-DESERIALIZE',
    title: 'ObjectInputStream.readObject',
    severity: 'critical',
    families: ['jvm'],
    pattern: /new\s+ObjectInputStream\s*\(|\.readObject\s*\(\s*\)/g,
    message: 'La deserialisation Java native permet l\'execution de gadgets.',
    suggestion: 'Utilisez un format de donnees (JSON, Protobuf) ou un filtre ObjectInputFilter strict.',
    cwe: 'CWE-502',
  },
  {
    id: 'SEC-PHP-UNSERIALIZE',
    title: 'unserialize() sur donnee externe',
    severity: 'critical',
    families: ['php'],
    pattern: /unserialize\s*\(/g,
    message: 'unserialize permet l\'instanciation d\'objets arbitraires (POP chain).',
    suggestion: 'Utilisez json_decode, ou unserialize($data, ["allowed_classes" => false]).',
    cwe: 'CWE-502',
  },

  // ------------------------------------------------------ Crypto & aleatoire
  {
    id: 'SEC-WEAK-HASH',
    title: 'Algorithme de hachage obsolete',
    severity: 'high',
    families: ['*'],
    pattern: /\b(md5|sha1)\s*\(|["'](MD5|SHA-?1)["']/gi,
    message: 'MD5/SHA-1 sont casses pour toute utilisation de securite.',
    suggestion: 'SHA-256+ pour l\'integrite ; bcrypt, scrypt ou Argon2id pour les mots de passe.',
    cwe: 'CWE-327',
    owasp: 'A02:2021 Cryptographic Failures',
    ignoreIf: (line) => /etag|cache|checksum|gravatar|hashCode/i.test(line),
  },
  {
    id: 'SEC-WEAK-CIPHER',
    title: 'Chiffrement faible ou mode ECB',
    severity: 'high',
    families: ['*'],
    pattern: /\b(DES|3DES|RC4|Blowfish)\b|AES\/ECB|MODE_ECB|["']aes-\d+-ecb["']/g,
    message: 'Algorithme ou mode de chiffrement non sur (ECB ne masque pas les motifs).',
    suggestion: 'Utilisez AES-256-GCM ou ChaCha20-Poly1305, avec un IV/nonce unique par message.',
    cwe: 'CWE-327',
    owasp: 'A02:2021 Cryptographic Failures',
  },
  {
    id: 'SEC-WEAK-RANDOM',
    title: 'Aleatoire non cryptographique',
    severity: 'medium',
    families: ['*'],
    pattern: /Math\.random\s*\(\)|new\s+Random\s*\(|random\.random\s*\(\)|rand\s*\(\)|mt_rand\s*\(/g,
    message: 'Generateur pseudo-aleatoire previsible.',
    suggestion: 'Pour un token, une clef ou un mot de passe : crypto.randomUUID(), crypto.getRandomValues, secrets.token_urlsafe, SecureRandom.',
    cwe: 'CWE-338',
    confidence: 'tentative',
    ignoreIf: (line) => /(color|anim|delay|jitter|shuffle|sample|demo|mock|seed)/i.test(line),
  },
  {
    id: 'SEC-TLS-DISABLED',
    title: 'Verification TLS desactivee',
    severity: 'critical',
    families: ['*'],
    pattern: /(rejectUnauthorized\s*:\s*false|verify\s*=\s*False|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]?0|InsecureSkipVerify\s*:\s*true|ALLOW_ALL_HOSTNAME_VERIFIER|setHostnameVerifier|badCertificateCallback)/g,
    message: 'La validation du certificat TLS est desactivee : le trafic est interceptable.',
    suggestion: 'Supprimez ce contournement. En developpement, ajoutez plutot le certificat local au magasin de confiance.',
    cwe: 'CWE-295',
    owasp: 'A02:2021 Cryptographic Failures',
  },
  {
    id: 'SEC-HTTP-URL',
    title: 'URL en HTTP non chiffre',
    severity: 'medium',
    families: ['*'],
    pattern: /["']http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\]|schemas?\.|www\.w3\.org|xmlns)[^"'\s]+["']/g,
    raw: true,
    // Un URI d'espace de noms XML n'est jamais telecharge : c'est un
    // identifiant, pas une adresse.
    ignoreIf: (line) => /xmlns|schemaLocation|namespace|<\?xml|\bDTD\b|maven\.apache\.org|w3\.org/i.test(line),
    message: 'Appel a une ressource externe en clair.',
    suggestion: 'Passez l\'URL en https:// et activez HSTS cote serveur.',
    cwe: 'CWE-319',
  },

  // ------------------------------------------------------- Auth & controles
  {
    id: 'SEC-JWT-NONE',
    title: 'JWT sans verification de signature',
    severity: 'critical',
    families: ['*'],
    pattern: /(algorithms?\s*[:=]\s*\[?\s*["']none["']|verify_signature\s*[:=]\s*False|jwt\.decode\s*\([^)]*verify\s*=\s*False|jwt\.decode\s*\([^),]+\)\s*[;,)])/g,
    message: 'Le jeton JWT est decode sans que sa signature soit verifiee.',
    suggestion: 'Utilisez jwt.verify (Node) ou jwt.decode(token, key, algorithms=["HS256"]) et refusez explicitement l\'algorithme "none".',
    cwe: 'CWE-347',
    owasp: 'A07:2021 Authentication Failures',
  },
  {
    id: 'SEC-CORS-WILDCARD',
    title: 'CORS ouvert a toutes les origines',
    severity: 'high',
    families: ['*'],
    pattern: /(Access-Control-Allow-Origin["']?\s*[,:=]\s*["']\*|origins?\s*[:=]\s*["']\*["']|cors\(\s*\)|allow_origins\s*=\s*\[\s*["']\*|allowedOrigins\s*\(\s*["']\*)/g,
    raw: true,
    message: 'Toutes les origines sont autorisees a appeler l\'API.',
    suggestion: 'Listez explicitement les origines de confiance ; * est incompatible avec credentials: true.',
    cwe: 'CWE-942',
    owasp: 'A05:2021 Security Misconfiguration',
  },
  {
    id: 'SEC-CSRF-OFF',
    title: 'Protection CSRF desactivee',
    severity: 'high',
    families: ['*'],
    pattern: /(csrf\s*[:=]\s*(false|False)|csrf_exempt|@CsrfExempt|WithCsrfProtection\(false\)|csrf\s*\(\s*\)?\s*\.\s*disable\s*\(|VerifyCsrfToken)/g,
    // Importer le decorateur ne desactive rien : seul son usage compte.
    ignoreIf: (line) => /^\s*(import|from|use)\b/.test(line),
    message: 'La protection CSRF est explicitement levee.',
    suggestion: 'Conservez le jeton CSRF, ou utilisez des cookies SameSite=Strict/Lax + verification d\'origine pour les API.',
    cwe: 'CWE-352',
  },
  {
    id: 'SEC-ALLOWED-HOSTS-WILDCARD',
    title: 'Hotes autorises non restreints',
    severity: 'high',
    families: ['python'],
    raw: true,
    pattern: /ALLOWED_HOSTS\s*=\s*\[[^\]]*['"]\*['"]/g,
    message: 'ALLOWED_HOSTS accepte n\'importe quel en-tete Host : empoisonnement de cache et liens de reinitialisation de mot de passe falsifiables.',
    suggestion: 'Listez vos domaines reels : ALLOWED_HOSTS = ["exemple.com", "www.exemple.com"]. En developpement, ajoutez seulement "localhost" et "127.0.0.1".',
    cwe: 'CWE-20',
    owasp: 'A05:2021 Security Misconfiguration',
  },
  {
    id: 'SEC-SECURE-FLAG-OFF',
    title: 'Cookie de session transmis en clair',
    severity: 'high',
    families: ['python', 'php', 'jvm', 'dotnet'],
    raw: true,
    pattern: /\b(?:SESSION_COOKIE_SECURE|CSRF_COOKIE_SECURE|SESSION_COOKIE_HTTPONLY|CSRF_COOKIE_HTTPONLY|cookie_secure|session\.cookie_secure)\s*=\s*(?:False|false|0)\b/g,
    message: 'Un drapeau de securite des cookies est explicitement desactive : le cookie de session peut circuler en HTTP ou etre lu par du JavaScript.',
    suggestion: 'Passez ces reglages a True en production. Pilotez-les par variable d\'environnement plutot que de les desactiver en dur.',
    cwe: 'CWE-614',
    owasp: 'A05:2021 Security Misconfiguration',
  },
  {
    id: 'SEC-COOKIE-FLAGS',
    title: 'Cookie sans httpOnly / secure',
    severity: 'medium',
    families: ['*'],
    pattern: /(httpOnly\s*:\s*false|secure\s*:\s*false|httponly\s*=\s*False|samesite\s*[:=]\s*["']?none)/gi,
    message: 'Cookie accessible en JavaScript ou transmis en clair.',
    suggestion: 'Positionnez httpOnly: true, secure: true et sameSite: "lax" (ou "strict") sur les cookies de session.',
    cwe: 'CWE-1004',
  },
  {
    id: 'SEC-PERMISSIVE-PERMS',
    title: 'Permissions de fichier trop larges',
    severity: 'medium',
    families: ['*'],
    pattern: /(chmod\s*\(?\s*["']?0?777|chmod\s+777|os\.chmod\([^)]*0o777|FileMode\(0777\))/g,
    message: 'Permissions 777 : le fichier est modifiable par tout utilisateur du systeme.',
    suggestion: 'Utilisez 0644 pour les fichiers et 0755 pour les dossiers ; 0600 pour les secrets.',
    cwe: 'CWE-732',
  },

  // ------------------------------------------------------------- Chemins/SSRF
  {
    id: 'SEC-PATH-TRAVERSAL',
    // La gravite depend de l'origine de la valeur concatenee : le flux
    // de donnees est consulte quand le fichier est du JavaScript.
    fluxDeDonnees: true,
    title: 'Chemin de fichier construit depuis une entree',
    severity: 'high',
    families: ['*'],
    pattern: /(readFile|readFileSync|createReadStream|open|sendFile|File\s*\(|Paths\.get|file_get_contents|fopen)\s*\([^)]*(req\.(params|query|body)|request\.(args|form|GET|POST)|params\[|\$_(GET|POST|REQUEST))/g,
    message: 'Un chemin de fichier depend directement d\'une entree utilisateur : traversee de repertoire possible.',
    suggestion: 'Normalisez avec path.resolve puis verifiez que le resultat commence par le repertoire autorise ; refusez sinon.',
    cwe: 'CWE-22',
    owasp: 'A01:2021 Broken Access Control',
  },
  {
    id: 'SEC-SSRF',
    // La gravite depend de l'origine de la valeur concatenee : le flux
    // de donnees est consulte quand le fichier est du JavaScript.
    fluxDeDonnees: true,
    title: 'Requete sortante vers une URL fournie',
    severity: 'high',
    families: ['*'],
    pattern: /(fetch|axios(\.\w+)?|requests\.(get|post|put)|http\.get|urlopen|HttpClient|curl_setopt)\s*\([^)]*(req\.(params|query|body)|request\.(args|form)|params\[|\$_(GET|POST))/g,
    message: 'L\'application appelle une URL controlee par le client : SSRF possible vers le reseau interne.',
    suggestion: 'Validez l\'URL contre une liste blanche de domaines et bloquez les plages privees (127.0.0.0/8, 169.254.0.0/16, 10.0.0.0/8).',
    cwe: 'CWE-918',
    owasp: 'A10:2021 SSRF',
  },
  {
    id: 'SEC-OPEN-REDIRECT',
    title: 'Redirection ouverte',
    severity: 'medium',
    families: ['*'],
    pattern: /(redirect_to|redirect|location\.href|location\.replace|sendRedirect)\s*[(=\s]\s*[^;)\n]*(req\.(query|params|body)|request\.(args|GET)|\$_(GET|REQUEST)|\$request->(input|query|get|all)\s*\(|params\[)/g,
    message: 'La cible de redirection provient de la requete : phishing possible.',
    suggestion: 'N\'acceptez que des chemins relatifs, ou validez le domaine cible contre une liste blanche.',
    cwe: 'CWE-601',
  },

  // ------------------------------------------------------------ Configuration
  {
    id: 'SEC-DEBUG-ON',
    title: 'Mode debug active',
    severity: 'medium',
    families: ['*'],
    pattern: /(DEBUG\s*[:=]\s*True|debug\s*[:=]\s*true|APP_DEBUG\s*=\s*true|app\.run\([^)]*debug\s*=\s*True)/g,
    message: 'Le mode debug expose les traces d\'erreur et parfois une console distante.',
    suggestion: 'Pilotez le mode debug par variable d\'environnement et forcez-le a false en production.',
    cwe: 'CWE-489',
    owasp: 'A05:2021 Security Misconfiguration',
    // `debug: true` apparait aussi dans des objets d'options anodins.
    confidence: 'tentative',
    ignoreIf: (line) => /\/\/|test|mock|story/i.test(line),
  },
  {
    id: 'SEC-BIND-ALL',
    title: 'Service ecoutant sur toutes les interfaces',
    severity: 'low',
    families: ['*'],
    pattern: /(host\s*[:=]\s*["']0\.0\.0\.0["']|listen\(\s*\d+\s*,\s*["']0\.0\.0\.0["'])/g,
    message: 'Le service est expose sur toutes les interfaces reseau.',
    suggestion: 'Ecoutez sur 127.0.0.1 derriere un reverse proxy, sauf besoin explicite.',
    cwe: 'CWE-1327',
    confidence: 'tentative',
  },
  {
    id: 'SEC-PROTOTYPE-POLLUTION',
    title: 'Pollution de prototype possible',
    severity: 'high',
    families: ['js'],
    // Restreinte aux affectations dont la clef vient manifestement de
    // l'exterieur : `obj[key] = value` sur des donnees locales est un idiome
    // parfaitement legitime et beaucoup trop frequent pour etre signale.
    pattern: /\[\s*(?:req|request|params|body|query|payload|input|userInput)\b[^\]]*\]\s*=[^=]|Object\.assign\s*\(\s*\w+\s*,\s*(?:req\.body|request\.body|JSON\.parse)|\bmerge(?:Deep)?\s*\(\s*\w+\s*,\s*(?:req\.body|JSON\.parse)/g,
    message: 'Affectation par clef issue d\'une entree utilisateur : une clef __proto__ peut polluer Object.prototype.',
    suggestion: 'Rejetez les clefs __proto__, constructor et prototype, ou utilisez Object.create(null) / Map.',
    cwe: 'CWE-1321',
    confidence: 'tentative',
  },
  {
    id: 'SEC-REGEX-DOS',
    title: 'Expression reguliere a risque de ReDoS',
    severity: 'medium',
    families: ['*'],
    pattern: /\(\s*[^)]*[+*]\s*\)\s*[+*]|\(\?:[^)]*[+*]\)[+*]/g,
    message: 'Quantificateurs imbriques : le temps d\'evaluation peut exploser sur une entree construite.',
    suggestion: 'Reecrivez le motif sans imbrication de quantificateurs, ou bornez la longueur de l\'entree.',
    cwe: 'CWE-1333',
    confidence: 'tentative',
  },
  {
    id: 'SEC-LOG-SENSITIVE',
    title: 'Donnee sensible potentiellement journalisee',
    severity: 'medium',
    families: ['*'],
    pattern: /(console\.(log|info|warn|error)|print|printf|logger?\.(info|debug|warn|error))\s*\([^)]*\b(password|passwd|mot_de_passe|token|secret|api_?key|authorization|credit_?card|ssn|iban)\b/gi,
    message: 'Un secret ou une donnee personnelle semble ecrit dans les logs.',
    suggestion: 'Masquez la valeur (4 derniers caracteres) ou retirez le champ avant journalisation.',
    cwe: 'CWE-532',
    owasp: 'A09:2021 Logging Failures',
  },
  {
    id: 'SEC-EMPTY-CATCH',
    title: 'Erreur silencieusement ignoree',
    severity: 'low',
    families: ['js', 'jvm', 'php', 'dart', 'dotnet'],
    // `raw` volontaire : sur le code masque, les commentaires sont effaces et
    // un `catch { /* raison documentee */ }` passerait pour un bloc vide. Or
    // c'est precisement ce que la regle demande de faire — la suggestion
    // consiste a expliquer pourquoi l'erreur est ignorable.
    raw: true,
    pattern: /catch\s*(\([^)]*\))?\s*\{\s*\}/g,
    message: 'Bloc catch vide et non commente : une defaillance peut passer totalement inapercue.',
    suggestion: 'Journalisez l\'erreur, ou laissez un commentaire expliquant pourquoi elle est sans consequence ici.',
    cwe: 'CWE-390',
  },
  {
    id: 'SEC-XXE',
    title: 'Parseur XML sans protection XXE',
    severity: 'high',
    families: ['*'],
    pattern: /(DocumentBuilderFactory\.newInstance|SAXParserFactory\.newInstance|etree\.parse|libxml_disable_entity_loader\s*\(\s*false|resolve_entities\s*=\s*True|XMLReader\s*\()/g,
    message: 'Parseur XML potentiellement vulnerable aux entites externes (XXE).',
    suggestion: 'Desactivez les DTD et les entites externes : setFeature("http://apache.org/xml/features/disallow-doctype-decl", true) ou defusedxml en Python.',
    cwe: 'CWE-611',
    owasp: 'A05:2021 Security Misconfiguration',
    confidence: 'tentative',
  },
  {
    id: 'SEC-MASS-ASSIGNMENT',
    title: 'Affectation de masse depuis le corps de requete',
    severity: 'medium',
    families: ['*'],
    // `::` pour Eloquent et les appels statiques PHP, `.` pour le reste.
    pattern: /(?:\.|::)(create|update|updateOrCreate|fill|save|new)\s*\(\s*(req\.body|request\.data|request\.POST|params|\$request->all\(\)|\$_POST)\s*\)/g,
    message: 'Le corps de la requete est passe tel quel au modele : un champ prive (role, isAdmin) peut etre force.',
    suggestion: 'Selectionnez explicitement les champs autorises avant l\'ecriture (DTO, schema de validation, fillable).',
    cwe: 'CWE-915',
    owasp: 'A01:2021 Broken Access Control',
  },
  {
    id: 'SEC-NO-RATE-LIMIT',
    title: 'Endpoint d\'authentification sans limitation de debit',
    severity: 'medium',
    families: ['*'],
    pattern: /(login|signin|signup|register|reset-?password|forgot-?password|otp|verify)/gi,
    scope: 'route',
    message: 'Route d\'authentification detectee : verifiez qu\'une limitation de debit est appliquee.',
    suggestion: 'Ajoutez un rate limiter (express-rate-limit, slowapi, bucket4j) et un verrouillage progressif apres echecs.',
    cwe: 'CWE-307',
    owasp: 'A07:2021 Authentication Failures',
    confidence: 'tentative',
  },
];

/**
 * Regles portant sur les fichiers de configuration / infrastructure.
 * Elles s'appliquent au contenu brut (pas de masquage).
 */
export const CONFIG_SECURITY_RULES = [
  {
    id: 'SEC-DOCKER-ROOT',
    title: 'Conteneur executant en root',
    severity: 'medium',
    files: /(^|\/)Dockerfile/i,
    check: (content) => !/^\s*USER\s+(?!root)/mi.test(content) && /^\s*FROM\s+/mi.test(content),
    message: 'Aucune directive USER non-root : le processus tourne en root dans le conteneur.',
    suggestion: 'Ajoutez `RUN adduser -D app` puis `USER app` avant CMD.',
    cwe: 'CWE-250',
  },
  {
    id: 'SEC-DOCKER-LATEST',
    title: 'Image de base non epinglee',
    severity: 'low',
    files: /(^|\/)Dockerfile/i,
    pattern: /^\s*FROM\s+\S+:latest/mi,
    message: 'FROM ...:latest rend les builds non reproductibles et peut introduire des regressions.',
    suggestion: 'Epinglez une version, idealement par digest : FROM node:22.3-alpine@sha256:…',
  },
  {
    id: 'SEC-ENV-COMMITTED',
    title: 'Fichier .env versionne',
    severity: 'critical',
    // Le suffixe d'exemple peut etre precede d'autres segments :
    // `.env.local.example` est un modele, pas un fichier d'environnement.
    files: /(^|\/)\.env(\.[\w.-]*)?$/,
    exclude: /\.(example|sample|template|dist|md|txt)$/i,
    check: (content) => /=\S/.test(content),
    message: 'Un fichier .env contenant des valeurs est present dans le depot.',
    suggestion: 'Ajoutez .env au .gitignore, faites tourner les secrets exposes, et versionnez un .env.example vide.',
    cwe: 'CWE-540',
  },
  {
    id: 'SEC-MISSING-HEADERS',
    title: 'En-tetes de securite HTTP absents',
    severity: 'medium',
    scope: 'project',
    message: 'Aucune configuration d\'en-tetes de securite detectee (CSP, HSTS, X-Frame-Options…).',
    suggestion: 'Ajoutez helmet (Node), SecurityMiddleware (Django), ou configurez-les dans nginx/Cloudflare : Content-Security-Policy, Strict-Transport-Security, X-Content-Type-Options, Referrer-Policy, Permissions-Policy.',
    cwe: 'CWE-693',
    owasp: 'A05:2021 Security Misconfiguration',
  },
];
